### ISSUE TITLE
Limited download abilities

### ISSUE THREAD

**Issue by BenjiDa** [BenjiDa/dem_loader#1]
Right now code is only set to download DEMs with file names of format like: 'USGS_NED_13_nXXwYYY_IMG.zip'

There are a large list of other types as well, including formats with no prefix: 'nXXwYYY.zip'

Code should be expanded to include searches of these files.

**Comment by millzpaugh** [comment]
This looks so awesome! I have a few suggestions related to how you can refactor your code. I've shared example code below that might be helpful addressing these points. 

1. Create a function that can pull down many files. That way, you don't have to run the script for each file!  

2. It looks like you can specify the outfile path, which might be helpful so you don't have to dig around and find where the file is downloaded locally. (This isn't necessary though!). https://stackoverflow.com/questions/24346872/python-equivalent-of-a-given-wget-command#28313383

3. The way your try/except handler is written, it will swallow errors and you don't normally want to do that. Since this is a test to continue running code for an odd USGS filenaming pattern, it seems to be solution for your use case. Generally you want to use try/except blocks to raise exceptions that give you a specific message and stack trace to the root of the error in your error logs. Right now, the exception is just running more code. 


```
URL = 'ftp://rockyftp.cr.usgs.gov/vdelivery/Datasets/Staged/NED/13/IMG/'
filenames = ['n39w122', 'fileb'] 

def retrieve_DEMS(filenames): 
  all_file_paths = build_file_paths(filenames) 

  for path in all_file_paths: 
    for k,v in path.iteritems(): 
      try:
        ftp_path = URL + v 
        wget.download(ftp_path, outfile='mydirectory/demfiles/')

      except URLError:
        print('%s does not exist' % ftp_path)
        continue

def build_file_paths(filenames):
  all_filename_possibilities = []
  for file in filenames: 
    #you can add as many odd filename builders here as you want
    f = {'short_name': file + '.zip', 'long_name':'USGS_NED_13_' + file + '.zip'}
    all_filename_possibilities.append(f)
  return all_filename_possibilities 
```

**Comment by millzpaugh** [comment]
After checking out your updated code, it looks like the filename is generated from lat/long points. I'd expand `build_file_paths` to build all the DEM filepaths based off of the coordinate inputs.

**Comment by BenjiDa** [comment]
Thanks for input! I think this would work. I was also playing with ftplib this morning as an option to download certain files, but didn't get too far.

**Comment by BenjiDa** [comment]
This is fixed, now takes a list of tuples and runs through all possible filenames. Closing.
